name: conditional job execution
on: [push]
jobs:
 job1: 
   runs-on: ubuntu-latest
   steps:
     - name: checkout code
       uses: actions/checkout@v3
     - name: Run a command
       run: echo "job one is running..."
 job2:
   runs-on: ubuntu-latest
   needs: job1
   if: success()
   steps:
     - name: run only when job 1 succeeds
       run: echo "Job 2 is running coz job 1 succeeded"
     - name: run this step only on the main branch
       run: echo "this step runs only on the main branch"
       
